### ISSUE TITLE
How to check array object

### ISSUE THREAD

**Issue by pawelotto** [lykmapipo/mongoose-exists#2]
Is there any way this plugin would support checking on array objects containing references to objects?

**Comment by lykmapipo** [comment]
sure...I guess it supported even though not documented...I will push specs and documentation for that

**Comment by pawelotto** [comment]
Thanks that would be HUGE help for me. BTW Excellent module!

**Comment by mattslight** [comment]
Hi - doesn't look like plugin is checking inside arrays. I see you tagged this as "enhancement" so I guess you are already working on it?

BTW - Great plugin - really helped me. Thank you for sharing.

**Comment by mattslight** [comment]
Example schema:-
```javascript
.Schema({
	students: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User', exists: true }], // exists checking doesn't seem to work
	tutor: { type: mongoose.Schema.Types.ObjectId, ref: 'User', exists: true } // // exists checking does work :)
})`

**Comment by lykmapipo** [comment]
@mattslight Yah...am pushing for enhancement

**Comment by lykmapipo** [comment]
@pawelotto & @mattslight v0.5.0 is out with fixes.

**Comment by pawelotto** [comment]
Thanks mate, gonna try it soon. Great module!

**Comment by mattslight** [comment]
Just returned to see this implemented. Great job guys.
